CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE TABLE "user" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        username character varying(50) NOT NULL,
        password text NOT NULL,
        user_type text NOT NULL,
        full_name character varying(200) NOT NULL,
        email text NOT NULL,
        mobile character varying(50) NOT NULL,
        company character varying(200) NOT NULL,
        last_login timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
        CONSTRAINT "PK_user" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE TABLE user_session (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token text NOT NULL,
        device text NOT NULL,
        location text NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
        expires_at timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC' + INTERVAL '7 DAYS'),
        CONSTRAINT "PK_user_session" PRIMARY KEY (id),
        CONSTRAINT "FK_user_session_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE UNIQUE INDEX "IX_user_email" ON "user" (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE UNIQUE INDEX "IX_user_username" ON "user" (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE UNIQUE INDEX "IX_user_session_token" ON user_session (token);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    CREATE INDEX "IX_user_session_user_id" ON user_session (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260223110728_CreateUserTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260223110728_CreateUserTable', '8.0.8');
    END IF;
END $EF$;
COMMIT;

